export { CatalogPages } from './CatalogPages/CatalogPages.async.tsx'
export { CartPage } from './CartPage/CartPage.async.tsx'
export { NotFound } from './NotFound/NotFound.async.tsx'
export { TattooMachineDetails } from './TattooMachineDetails/TattooMachineDetails.async.tsx'
export { DiscountPage } from './DiscountPage/DiscountPage.async.tsx'
export { AdditionalServicePage } from './AdditionalServicePage/AdditionalServicePage.async.tsx'
export { PromocodesPage } from './PromocodesPage/PromocodesPage.async.tsx'