export { Catalog } from './Catalog/Catalog.tsx'
export { NavBar } from './NavBar/NavBar.tsx'
export { FilterToolbar } from './FilterToolbar/FilterToolbar.tsx'
export { AdditionalCartInfo } from './AdditionalCartInfo/AdditionalCartInfo.tsx'
export { OrderHistory } from '@/widgets/OrderHistory/OrderHistory.tsx'